//! Create the `sessions` table — one operating or monitoring run.
//!
//! A session groups the transmissions heard during a single stretch of operating: a
//! casual monitor run, a net, a contest, a POTA activation. It is the parent of
//! `observations`, and it carries the radio metadata that a receive-only monitor can't
//! discover for itself (band, mode, frequency) because there is no rig control.
//!
//! `client_key` is generated by the client, not the server. That is what lets a desktop
//! app open a session while completely offline: it never has to learn a server-assigned
//! id, so a run recorded with the site unreachable reconstructs itself correctly
//! whenever connectivity returns — even after a restart.

use sea_orm_migration::{prelude::*, schema::*};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Sessions::Table)
                    .if_not_exists()
                    .col(pk_auto(Sessions::Id))
                    .col(big_integer(Sessions::UserId))
                    .col(string(Sessions::ClientKey))
                    .col(string(Sessions::Kind))
                    .col(string_null(Sessions::Label))
                    .col(timestamp_with_time_zone(Sessions::StartedAt))
                    .col(timestamp_with_time_zone_null(Sessions::EndedAt))
                    .col(string_null(Sessions::Band))
                    .col(string_null(Sessions::Mode))
                    .col(double_null(Sessions::FrequencyMhz))
                    .col(string_null(Sessions::OperatorCallsign))
                    .col(string_null(Sessions::Grid))
                    .col(string_null(Sessions::Source))
                    .col(text_null(Sessions::Notes))
                    .col(timestamp_with_time_zone(Sessions::CreatedAt))
                    .col(timestamp_with_time_zone(Sessions::UpdatedAt))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_sessions_user_id")
                    .table(Sessions::Table)
                    .col(Sessions::UserId)
                    .to_owned(),
            )
            .await?;

        // Uniqueness is per user, not global: two operators may independently generate
        // the same key, and scoping it to the owner is what makes the upsert-by-key
        // ingest path safe.
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("uq_sessions_user_client_key")
                    .table(Sessions::Table)
                    .col(Sessions::UserId)
                    .col(Sessions::ClientKey)
                    .unique()
                    .to_owned(),
            )
            .await?;

        // The sessions list is always "this user, newest first".
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_sessions_user_started_at")
                    .table(Sessions::Table)
                    .col(Sessions::UserId)
                    .col(Sessions::StartedAt)
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Sessions::Table).to_owned())
            .await
    }
}

/// Column identifiers; kept in sync with `entity::sessions::Model`.
#[derive(DeriveIden)]
enum Sessions {
    Table,
    Id,
    UserId,
    ClientKey,
    Kind,
    Label,
    StartedAt,
    EndedAt,
    Band,
    Mode,
    FrequencyMhz,
    OperatorCallsign,
    Grid,
    Source,
    Notes,
    CreatedAt,
    UpdatedAt,
}
